name: Adding Two Numbers

on:
  workflow_dispatch:
    inputs:
      number1:
        description: 'First number'
        required: true
        default: '0'
      number2:
        description: 'Second number'
        required: true
        default: '0'

jobs:
  add-numbers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Python script to add numbers
      run: |
        python3 add_numbers.py ${{ github.event.inputs.number1 }} ${{ github.event.inputs.number2 }}
